# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import *
from functions import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(970, 649)
        Form.setFixedSize(970,649)   #Fixing the Size
        self.gridLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(5, 243, 961, 321))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.Overview = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.Overview.setContentsMargins(0, 0, 0, 0)
        self.Overview.setSpacing(1)
        self.Overview.setObjectName("Overview")
        self.Right = QtWidgets.QGridLayout()
        self.Right.setSpacing(1)
        self.Right.setObjectName("Right")
        self.R7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R7.setAlignment(QtCore.Qt.AlignCenter)
        self.R7.setObjectName("R7")
        self.Right.addWidget(self.R7, 2, 0, 1, 1)
        self.R9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R9.setAlignment(QtCore.Qt.AlignCenter)
        self.R9.setObjectName("R9")
        self.Right.addWidget(self.R9, 2, 2, 1, 1)
        self.R6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R6.setAlignment(QtCore.Qt.AlignCenter)
        self.R6.setObjectName("R6")
        self.Right.addWidget(self.R6, 1, 2, 1, 1)
        self.R5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R5.setAlignment(QtCore.Qt.AlignCenter)
        self.R5.setObjectName("R5")
        self.Right.addWidget(self.R5, 1, 1, 1, 1)
        self.R8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R8.setAlignment(QtCore.Qt.AlignCenter)
        self.R8.setObjectName("R8")
        self.Right.addWidget(self.R8, 2, 1, 1, 1)
        self.R4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R4.setAlignment(QtCore.Qt.AlignCenter)
        self.R4.setObjectName("R4")
        self.Right.addWidget(self.R4, 1, 0, 1, 1)
        self.R3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R3.setAlignment(QtCore.Qt.AlignCenter)
        self.R3.setObjectName("R3")
        self.Right.addWidget(self.R3, 0, 2, 1, 1)
        self.R2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R2.setAlignment(QtCore.Qt.AlignCenter)
        self.R2.setObjectName("R2")
        self.Right.addWidget(self.R2, 0, 1, 1, 1)
        self.R1 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.R1.setAlignment(QtCore.Qt.AlignCenter)
        self.R1.setObjectName("R1")
        self.Right.addWidget(self.R1, 0, 0, 1, 1)
        self.Overview.addLayout(self.Right, 1, 2, 1, 1)
        self.Back = QtWidgets.QGridLayout()
        self.Back.setSpacing(1)
        self.Back.setObjectName("Back")
        self.B7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B7.setAlignment(QtCore.Qt.AlignCenter)
        self.B7.setObjectName("B7")
        self.Back.addWidget(self.B7, 2, 0, 1, 1)
        self.B4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B4.setAlignment(QtCore.Qt.AlignCenter)
        self.B4.setObjectName("B4")
        self.Back.addWidget(self.B4, 1, 0, 1, 1)
        self.B6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B6.setAlignment(QtCore.Qt.AlignCenter)
        self.B6.setObjectName("B6")
        self.Back.addWidget(self.B6, 1, 2, 1, 1)
        self.B9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B9.setAlignment(QtCore.Qt.AlignCenter)
        self.B9.setObjectName("B9")
        self.Back.addWidget(self.B9, 2, 2, 1, 1)
        self.B5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B5.setAlignment(QtCore.Qt.AlignCenter)
        self.B5.setObjectName("B5")
        self.Back.addWidget(self.B5, 1, 1, 1, 1)
        self.B8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B8.setAlignment(QtCore.Qt.AlignCenter)
        self.B8.setObjectName("B8")
        self.Back.addWidget(self.B8, 2, 1, 1, 1)
        self.B3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B3.setAlignment(QtCore.Qt.AlignCenter)
        self.B3.setObjectName("B3")
        self.Back.addWidget(self.B3, 0, 2, 1, 1)
        self.B2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B2.setAlignment(QtCore.Qt.AlignCenter)
        self.B2.setObjectName("B2")
        self.Back.addWidget(self.B2, 0, 1, 1, 1)
        self.B1 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.B1.setAlignment(QtCore.Qt.AlignCenter)
        self.B1.setObjectName("B1")
        self.Back.addWidget(self.B1, 0, 0, 1, 1)
        self.Overview.addLayout(self.Back, 1, 3, 1, 1)
        self.Down = QtWidgets.QGridLayout()
        self.Down.setSpacing(1)
        self.Down.setObjectName("Down")
        self.D5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D5.setAlignment(QtCore.Qt.AlignCenter)
        self.D5.setObjectName("D5")
        self.Down.addWidget(self.D5, 1, 1, 1, 1)
        self.D8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D8.setAlignment(QtCore.Qt.AlignCenter)
        self.D8.setObjectName("D8")
        self.Down.addWidget(self.D8, 2, 1, 1, 1)
        self.D7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D7.setAlignment(QtCore.Qt.AlignCenter)
        self.D7.setObjectName("D7")
        self.Down.addWidget(self.D7, 2, 0, 1, 1)
        self.D1 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D1.setAlignment(QtCore.Qt.AlignCenter)
        self.D1.setObjectName("D1")
        self.Down.addWidget(self.D1, 0, 0, 1, 1)
        self.D4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D4.setAlignment(QtCore.Qt.AlignCenter)
        self.D4.setObjectName("D4")
        self.Down.addWidget(self.D4, 1, 0, 1, 1)
        self.D2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D2.setAlignment(QtCore.Qt.AlignCenter)
        self.D2.setObjectName("D2")
        self.Down.addWidget(self.D2, 0, 1, 1, 1)
        self.D3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D3.setAlignment(QtCore.Qt.AlignCenter)
        self.D3.setObjectName("D3")
        self.Down.addWidget(self.D3, 0, 2, 1, 1)
        self.D6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D6.setAlignment(QtCore.Qt.AlignCenter)
        self.D6.setObjectName("D6")
        self.Down.addWidget(self.D6, 1, 2, 1, 1)
        self.D9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.D9.setAlignment(QtCore.Qt.AlignCenter)
        self.D9.setObjectName("D9")
        self.Down.addWidget(self.D9, 2, 2, 1, 1)
        self.Overview.addLayout(self.Down, 2, 1, 1, 1)
        self.Left = QtWidgets.QGridLayout()
        self.Left.setSpacing(1)
        self.Left.setObjectName("Left")
        self.L7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L7.setAlignment(QtCore.Qt.AlignCenter)
        self.L7.setObjectName("L7")
        self.Left.addWidget(self.L7, 2, 0, 1, 1)
        self.L4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L4.setAlignment(QtCore.Qt.AlignCenter)
        self.L4.setObjectName("L4")
        self.Left.addWidget(self.L4, 1, 0, 1, 1)
        self.L9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L9.setAlignment(QtCore.Qt.AlignCenter)
        self.L9.setObjectName("L9")
        self.Left.addWidget(self.L9, 2, 2, 1, 1)
        self.L5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L5.setAlignment(QtCore.Qt.AlignCenter)
        self.L5.setObjectName("L5")
        self.Left.addWidget(self.L5, 1, 1, 1, 1)
        self.L8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L8.setAlignment(QtCore.Qt.AlignCenter)
        self.L8.setObjectName("L8")
        self.Left.addWidget(self.L8, 2, 1, 1, 1)
        self.L6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L6.setAlignment(QtCore.Qt.AlignCenter)
        self.L6.setObjectName("L6")
        self.Left.addWidget(self.L6, 1, 2, 1, 1)
        self.L3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L3.setAlignment(QtCore.Qt.AlignCenter)
        self.L3.setObjectName("L3")
        self.Left.addWidget(self.L3, 0, 2, 1, 1)
        self.L2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L2.setAlignment(QtCore.Qt.AlignCenter)
        self.L2.setObjectName("L2")
        self.Left.addWidget(self.L2, 0, 1, 1, 1)
        self.L1 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.L1.setAlignment(QtCore.Qt.AlignCenter)
        self.L1.setObjectName("L1")
        self.Left.addWidget(self.L1, 0, 0, 1, 1)
        self.Overview.addLayout(self.Left, 1, 0, 1, 1)
        self.Up = QtWidgets.QGridLayout()
        self.Up.setSpacing(1)
        self.Up.setObjectName("Up")
        self.U8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U8.setAlignment(QtCore.Qt.AlignCenter)
        self.U8.setObjectName("U8")
        self.Up.addWidget(self.U8, 2, 1, 1, 1)
        self.U5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U5.setAlignment(QtCore.Qt.AlignCenter)
        self.U5.setObjectName("U5")
        self.Up.addWidget(self.U5, 1, 1, 1, 1)
        self.U6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U6.setAlignment(QtCore.Qt.AlignCenter)
        self.U6.setObjectName("U6")
        self.Up.addWidget(self.U6, 1, 2, 1, 1)
        self.U9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U9.setAlignment(QtCore.Qt.AlignCenter)
        self.U9.setObjectName("U9")
        self.Up.addWidget(self.U9, 2, 2, 1, 1)
        self.U4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U4.setTextFormat(QtCore.Qt.AutoText)
        self.U4.setAlignment(QtCore.Qt.AlignCenter)
        self.U4.setObjectName("U4")
        self.Up.addWidget(self.U4, 1, 0, 1, 1)
        self.U7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U7.setAlignment(QtCore.Qt.AlignCenter)
        self.U7.setObjectName("U7")
        self.Up.addWidget(self.U7, 2, 0, 1, 1)
        self.U3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U3.setAlignment(QtCore.Qt.AlignCenter)
        self.U3.setObjectName("U3")
        self.Up.addWidget(self.U3, 0, 2, 1, 1)
        self.U1 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U1.setAlignment(QtCore.Qt.AlignCenter)
        self.U1.setObjectName("U1")
        self.Up.addWidget(self.U1, 0, 0, 1, 1)
        self.U2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.U2.setAlignment(QtCore.Qt.AlignCenter)
        self.U2.setObjectName("U2")
        self.Up.addWidget(self.U2, 0, 1, 1, 1)
        self.Overview.addLayout(self.Up, 0, 1, 1, 1)
        self.Front = QtWidgets.QGridLayout()
        self.Front.setSpacing(1)
        self.Front.setObjectName("Front")
        self.F1 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F1.setAlignment(QtCore.Qt.AlignCenter)
        self.F1.setObjectName("F1")
        self.Front.addWidget(self.F1, 0, 0, 1, 1)
        self.F9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F9.setAlignment(QtCore.Qt.AlignCenter)
        self.F9.setObjectName("F9")
        self.Front.addWidget(self.F9, 2, 2, 1, 1)
        self.F4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F4.setAlignment(QtCore.Qt.AlignCenter)
        self.F4.setObjectName("F4")
        self.Front.addWidget(self.F4, 1, 0, 1, 1)
        self.F2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F2.setAlignment(QtCore.Qt.AlignCenter)
        self.F2.setObjectName("F2")
        self.Front.addWidget(self.F2, 0, 1, 1, 1)
        self.F6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F6.setAlignment(QtCore.Qt.AlignCenter)
        self.F6.setObjectName("F6")
        self.Front.addWidget(self.F6, 1, 2, 1, 1)
        self.F5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F5.setAlignment(QtCore.Qt.AlignCenter)
        self.F5.setObjectName("F5")
        self.Front.addWidget(self.F5, 1, 1, 1, 1)
        self.F7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F7.setAlignment(QtCore.Qt.AlignCenter)
        self.F7.setObjectName("F7")
        self.Front.addWidget(self.F7, 2, 0, 1, 1)
        self.F8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F8.setAlignment(QtCore.Qt.AlignCenter)
        self.F8.setObjectName("F8")
        self.Front.addWidget(self.F8, 2, 1, 1, 1)
        self.F3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.F3.setAlignment(QtCore.Qt.AlignCenter)
        self.F3.setObjectName("F3")
        self.Front.addWidget(self.F3, 0, 2, 1, 1)
        self.Overview.addLayout(self.Front, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(5, 1, 961, 241))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.ImageLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.ImageLayout.setContentsMargins(0, 0, 0, 0)
        self.ImageLayout.setSpacing(1)
        self.ImageLayout.setObjectName("ImageLayout")
        self.LeftCamera = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.LeftCamera.setText("")
        self.LeftCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.LeftCamera.setObjectName("LeftCamera")
        self.ImageLayout.addWidget(self.LeftCamera)
        self.BackCamera = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.BackCamera.setText("")
        self.BackCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.BackCamera.setObjectName("BackCamera")
        self.ImageLayout.addWidget(self.BackCamera)
        self.DownCamera_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.DownCamera_1.setText("")
        self.DownCamera_1.setAlignment(QtCore.Qt.AlignCenter)
        self.DownCamera_1.setObjectName("DownCamera_1")
        self.ImageLayout.addWidget(self.DownCamera_1)
        self.DownCamera_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.DownCamera_2.setText("")
        self.DownCamera_2.setAlignment(QtCore.Qt.AlignCenter)
        self.DownCamera_2.setObjectName("DownCamera_2")
        self.ImageLayout.addWidget(self.DownCamera_2)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(727, 565, 238, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.SolutionLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.SolutionLayout.setContentsMargins(0, 0, 0, 0)
        self.SolutionLayout.setSpacing(3)
        self.SolutionLayout.setObjectName("SolutionLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.SolutionLayout.addWidget(self.label_2)
        self.Solution = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Solution.setObjectName("Solution")
        self.SolutionLayout.addWidget(self.Solution)
        self.SovleButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SovleButton.setObjectName("SovleButton")
        self.SolutionLayout.addWidget(self.SovleButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(5, 565, 239, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.ResultLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.ResultLayout.setContentsMargins(0, 0, 0, 0)
        self.ResultLayout.setSpacing(0)
        self.ResultLayout.setObjectName("ResultLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.ResultLayout.addWidget(self.label)
        self.Result = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Result.setText("")
        self.Result.setObjectName("Result")
        self.ResultLayout.addWidget(self.Result)
        self.Recognize = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Recognize.setObjectName("Recognize")
        self.ResultLayout.addWidget(self.Recognize)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(246, 565, 239, 81))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.ColorCorrectionLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.ColorCorrectionLayout.setContentsMargins(0, 0, 0, 0)
        self.ColorCorrectionLayout.setSpacing(3)
        self.ColorCorrectionLayout.setObjectName("ColorCorrectionLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.ColorCorrectionLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Position = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.Position.setObjectName("Position")
        self.horizontalLayout.addWidget(self.Position)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.Color = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.Color.setClearButtonEnabled(False)
        self.Color.setObjectName("Color")
        self.horizontalLayout.addWidget(self.Color)
        self.ColorCorrectionLayout.addLayout(self.horizontalLayout)
        self.CorrectButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.CorrectButton.setObjectName("CorrectButton")
        self.ColorCorrectionLayout.addWidget(self.CorrectButton)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(487, 565, 238, 81))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.VerificationLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.VerificationLayout.setContentsMargins(0, 0, 0, 0)
        self.VerificationLayout.setSpacing(0)
        self.VerificationLayout.setObjectName("VerificationLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.VerificationLayout.addWidget(self.label_5)
        self.Result_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Result_2.setText("")
        self.Result_2.setObjectName("Result_2")
        self.VerificationLayout.addWidget(self.Result_2)
        self.VerifyButton = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.VerifyButton.setObjectName("VerifyButton")
        self.VerificationLayout.addWidget(self.VerifyButton)
        self.setStyleSheet(Form)
        self.retranslateUi(Form)
        
        self.click_connecting()
        # self.setPics()

        QtCore.QMetaObject.connectSlotsByName(Form)

    def setPics(self):
        self.size = QSize(239, 239)
        img_L = QImage('images/marked/image_L.jpg')
        jpg_L = QPixmap.fromImage(img_L.scaled(self.size))
        self.LeftCamera.setPixmap(jpg_L)
        img_B = QImage('images/marked/image_B.jpg')
        jpg_B = QPixmap.fromImage(img_B.scaled(self.size))
        self.BackCamera.setPixmap(jpg_B)
        img_D1 = QImage('images/marked/image_D1.jpg')
        jpg_D1 = QPixmap.fromImage(img_D1.scaled(self.size))
        self.DownCamera_1.setPixmap(jpg_D1)
        img_D2 = QImage('images/marked/image_D2.jpg')
        jpg_D2 = QPixmap.fromImage(img_D2.scaled(self.size))
        self.DownCamera_2.setPixmap(jpg_D2)



    def setStyleSheet(self, Form):
        self.F1.setStyleSheet("border: 1px solid red")
        self.F2.setStyleSheet("border: 1px solid red")
        self.F3.setStyleSheet("border: 1px solid red")
        self.F4.setStyleSheet("border: 1px solid red")
        self.F5.setStyleSheet("border: 1px solid red")
        self.F6.setStyleSheet("border: 1px solid red")
        self.F7.setStyleSheet("border: 1px solid red")
        self.F8.setStyleSheet("border: 1px solid red")
        self.F9.setStyleSheet("border: 1px solid red")
        self.B1.setStyleSheet("border: 1px solid red")
        self.B2.setStyleSheet("border: 1px solid red")
        self.B3.setStyleSheet("border: 1px solid red")
        self.B4.setStyleSheet("border: 1px solid red")
        self.B5.setStyleSheet("border: 1px solid red")
        self.B6.setStyleSheet("border: 1px solid red")
        self.B7.setStyleSheet("border: 1px solid red")
        self.B8.setStyleSheet("border: 1px solid red")
        self.B9.setStyleSheet("border: 1px solid red")
        self.L1.setStyleSheet("border: 1px solid red")
        self.L2.setStyleSheet("border: 1px solid red")
        self.L3.setStyleSheet("border: 1px solid red")
        self.L4.setStyleSheet("border: 1px solid red")
        self.L5.setStyleSheet("border: 1px solid red")
        self.L6.setStyleSheet("border: 1px solid red")
        self.L7.setStyleSheet("border: 1px solid red")
        self.L8.setStyleSheet("border: 1px solid red")
        self.L9.setStyleSheet("border: 1px solid red")
        self.R1.setStyleSheet("border: 1px solid red")
        self.R2.setStyleSheet("border: 1px solid red")
        self.R3.setStyleSheet("border: 1px solid red")
        self.R4.setStyleSheet("border: 1px solid red")
        self.R5.setStyleSheet("border: 1px solid red")
        self.R6.setStyleSheet("border: 1px solid red")
        self.R7.setStyleSheet("border: 1px solid red")
        self.R8.setStyleSheet("border: 1px solid red")
        self.R9.setStyleSheet("border: 1px solid red")
        self.U1.setStyleSheet("border: 1px solid red")
        self.U2.setStyleSheet("border: 1px solid red")
        self.U3.setStyleSheet("border: 1px solid red")
        self.U4.setStyleSheet("border: 1px solid red")
        self.U5.setStyleSheet("border: 1px solid red")
        self.U6.setStyleSheet("border: 1px solid red")
        self.U7.setStyleSheet("border: 1px solid red")
        self.U8.setStyleSheet("border: 1px solid red")
        self.U9.setStyleSheet("border: 1px solid red")
        self.D1.setStyleSheet("border: 1px solid red")
        self.D2.setStyleSheet("border: 1px solid red")
        self.D3.setStyleSheet("border: 1px solid red")
        self.D4.setStyleSheet("border: 1px solid red")
        self.D5.setStyleSheet("border: 1px solid red")
        self.D6.setStyleSheet("border: 1px solid red")
        self.D7.setStyleSheet("border: 1px solid red")
        self.D8.setStyleSheet("border: 1px solid red")
        self.D9.setStyleSheet("border: 1px solid red")
        self.label.setStyleSheet("border: 1px solid black")
        self.label_3.setStyleSheet("border: 1px solid black")
        self.label_2.setStyleSheet("border: 1px solid black")
        self.label_5.setStyleSheet("border: 1px solid black")
        self.LeftCamera.setStyleSheet("border: 1px solid black")
        self.BackCamera.setStyleSheet("border: 1px solid black")
        self.DownCamera_1.setStyleSheet("border: 1px solid black")
        self.DownCamera_2.setStyleSheet("border: 1px solid black")
        # self.Result.setStyleSheet("border: 1px solid black")
    

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Rubik's Cube Solver"))
        self.R7.setText(_translate("Form", "R7"))
        self.R9.setText(_translate("Form", "R9"))
        self.R6.setText(_translate("Form", "R6"))
        self.R5.setText(_translate("Form", "R5"))
        self.R8.setText(_translate("Form", "R8"))
        self.R4.setText(_translate("Form", "R4"))
        self.R3.setText(_translate("Form", "R3"))
        self.R2.setText(_translate("Form", "R2"))
        self.R1.setText(_translate("Form", "R1"))
        self.B7.setText(_translate("Form", "B7"))
        self.B4.setText(_translate("Form", "B4"))
        self.B6.setText(_translate("Form", "B6"))
        self.B9.setText(_translate("Form", "B9"))
        self.B5.setText(_translate("Form", "B5"))
        self.B8.setText(_translate("Form", "B8"))
        self.B3.setText(_translate("Form", "B3"))
        self.B2.setText(_translate("Form", "B2"))
        self.B1.setText(_translate("Form", "B1"))
        self.D5.setText(_translate("Form", "D5"))
        self.D8.setText(_translate("Form", "D8"))
        self.D7.setText(_translate("Form", "D7"))
        self.D1.setText(_translate("Form", "D1"))
        self.D4.setText(_translate("Form", "D4"))
        self.D2.setText(_translate("Form", "D2"))
        self.D3.setText(_translate("Form", "D3"))
        self.D6.setText(_translate("Form", "D6"))
        self.D9.setText(_translate("Form", "D9"))
        self.L7.setText(_translate("Form", "L7"))
        self.L4.setText(_translate("Form", "L4"))
        self.L9.setText(_translate("Form", "L9"))
        self.L5.setText(_translate("Form", "L5"))
        self.L8.setText(_translate("Form", "L8"))
        self.L6.setText(_translate("Form", "L6"))
        self.L3.setText(_translate("Form", "L3"))
        self.L2.setText(_translate("Form", "L2"))
        self.L1.setText(_translate("Form", "L1"))
        self.U8.setText(_translate("Form", "U8"))
        self.U5.setText(_translate("Form", "U5"))
        self.U6.setText(_translate("Form", "U6"))
        self.U9.setText(_translate("Form", "U9"))
        self.U4.setText(_translate("Form", "U4"))
        self.U7.setText(_translate("Form", "U7"))
        self.U3.setText(_translate("Form", "U3"))
        self.U1.setText(_translate("Form", "U1"))
        self.U2.setText(_translate("Form", "U2"))
        self.F1.setText(_translate("Form", "F1"))
        self.F9.setText(_translate("Form", "F9"))
        self.F4.setText(_translate("Form", "F4"))
        self.F2.setText(_translate("Form", "F2"))
        self.F6.setText(_translate("Form", "F6"))
        self.F5.setText(_translate("Form", "F5"))
        self.F7.setText(_translate("Form", "F7"))
        self.F8.setText(_translate("Form", "F8"))
        self.F3.setText(_translate("Form", "F3"))
        self.label_2.setText(_translate("Form", "Solution:"))
        self.SovleButton.setText(_translate("Form", "Solve"))
        self.label.setText(_translate("Form", "Result:"))
        self.Recognize.setText(_translate("Form", "Recognize"))
        self.label_3.setText(_translate("Form", "Color correction:"))
        self.Position.setPlaceholderText(_translate("Form", "Position"))
        self.label_4.setText(_translate("Form", "       is       "))
        self.Color.setPlaceholderText(_translate("Form", "Color"))
        self.CorrectButton.setText(_translate("Form", "Correct"))
        self.label_5.setText(_translate("Form", "Verification:"))
        self.VerifyButton.setText(_translate("Form", "Verify"))


    def click_connecting(self):
        self.Recognize.clicked.connect(self.push_recognize_button)
        self.CorrectButton.clicked.connect(self.push_correct_button)
        self.VerifyButton.clicked.connect(self.push_verify_button)
        self.SovleButton.clicked.connect(self.push_solve_button)

    def push_recognize_button(self):
        catch_frames()
        detect()
        self.setPics()

    def push_correct_button(self):
        communicate(self.Solution.text())

    def push_verify_button(self):
        communicate(self.Solution.text())

    def push_solve_button(self):
        communicate(self.Solution.text())


